POST http://localhost:3000/register
Content-Type: application/json

{
    "email" : "aunglin@gmail.com",
    "password" : "066813aunglin"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "email" : "aunglin@gmail.com",
    "password" : "066813aunglin"
}

###

GET http://localhost:3000/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF1bmdsaW5AZ21haWwuY29tIiwiaWF0IjoxNzA4NDQyNDc1fQ.NIV3_vA-r2EZU45IzStt0UtiO0_cM3EBViLKcX6lRec